---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: stg
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:stefanprodan/podinfo
    ref: master
    path: charts/podinfo
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 5.1.1
    service:
      enabled: false
      type: ClusterIP
    podAnnotations:
      sidecar.istio.io/inject: "true"
      checksum: 21315af252aa37cd100f349476ff71f0ab13bcc5

