apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
  namespace: stg
  annotations:
    fluxcd.io/ignore: "false"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  service:
    # container port
    port: 9898
    trafficPolicy:
      tls:
        # use ISTIO_MUTUAL when mTLS is enabled
        mode: DISABLE
    # Istio gateways (optional)
    gateways:
    - public-gateway.istio-system.svc.cluster.local
    # Istio virtual service host names (optional)
    hosts:
    - "podinfo.stg.digital"
   # match:
   # - uri:
   #     exact: podinfo
  analysis:
    interval: 15s
    threshold: 10
    iterations: 10
    match:
      - headers:
          user-agent:
            regex: ".*Firefox.*"
            #regex: "^(?!.*(?:Chrome|Edge)).*Safari"
      - headers:
          cookie:
            regex: "^(.*?;)?(type=insider)(;.*)?$"
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 30s
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://load-tester.stg/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -sd 'test' http://podinfo-canary.stg:9898/token | grep token"
      - name: smoke-test
        type: pre-rollout
        url: http://flagger-loadtester.stg/
        timeout: 3m
        metadata:
          type: helmv3
          cmd: test podinfo --cleanup --timeuout 3m --namespace stg
      - name: load-test
        type: rollout
        url: http://flagger-loadtester.stg/
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 -H 'Cookie: type=insider' http://podinfo-canary.stg:9898/"
