kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: prod
  labels:
    app: frontend
    managed-by: nij4t
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9898
      targetPort: 9898
  selector:
    app: frontend
  type: ClusterIP

